POST http://127.0.0.1:8000/ventas/ HTTP/1.1
Content-Type: application/json

{
    "idCliente": 1,
    "idEmpleado": 1,
    "estadoVenta": "VAL",
    "itemsProductos": [
        {
            "producto": 1,
            "cantidad": 3
        }
    ]
}

###

POST http://127.0.0.1:8000/proveedores/ HTTP/1.1
Content-Type: application/json

{
    "riffProveedor": 12345,
    "nombreProveedor": "Pollos Recao",
    "email": "recao@email.com",
    "telefonoProveedor": "04128187272",
    "direccionProveedor": "Via Perija"
}

###


POST http://127.0.0.1:8000/compras/ HTTP/1.1
Content-Type: application/json

{
    "idProveedor": 4,
    "estadoCompra": "VAL",
    "itemsProductosCompra": [
        {
            "producto": 1,
            "cantidad": 1
        }
    ]
}

###

GET http://127.0.0.1:8000/ventas/por-fechas/?fecha_inicio=2025-07-01&fecha_fin=2025-07-05

###
PATCH  http://127.0.0.1:8000/compra/1 HTTP/1.1
Content-Type: application/json

{
    "estadoCompra": "ANUL"
}

###

### Crear nuevo usuario desde email de empleado
POST http://127.0.0.1:8000/registro_usuario/
Content-Type: application/json

{
  "email": "fabiandduranj@gmail.com",
  "password": "26638389"
}

### Iniciar sesión con email usando JWT
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
   "email": "fabiandduranj@gmail.com",
  "password": "26638389"
}

### Solicitar código de recuperación
POST http://localhost:8000/solicitar-codigo/
Content-Type: application/json

{
  "email": "fabiandduranj@gmail.com"
}


###Verificar codigo

curl -X POST http://localhost:8000/verificar-codigo/ \
-H "Content-Type: application/json" \
-d '{"email":"fabiandduranj@gmail.com", "codigo":"894078"}'

### Cambiar contraseña (requiere token temporal)
curl -X POST http://localhost:8000/cambiar-contrasena/ \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNTQ1NzE5LCJpYXQiOjE3NTM1NDUxMTksImp0aSI6IjJkZDIwMzNiYWM2MTQ2NWRhMTA3YmIzZTc2MGJiODI1IiwidXNlcl9pZCI6Mn0.ixbo6s7jLWSIoVeaSmmWbzpHN_h_s8LaUFq-SIY5md4" \
-d '{"nueva_contrasena": "26638389a"}'