POST http://127.0.0.1:8000/ventas/ HTTP/1.1
Content-Type: application/json

{
    "idCliente": 1,
    "idEmpleado": 1,
    "estadoVenta": "VAL",
    "itemsProductos": [
        {
            "producto": 1,
            "cantidad": 3
        }
    ]
}

###

POST http://127.0.0.1:8000/proveedores/ HTTP/1.1
Content-Type: application/json

{
    "riffProveedor": 12345,
    "nombreProveedor": "Pollos Recao",
    "email": "recao@email.com",
    "telefonoProveedor": "04128187272",
    "direccionProveedor": "Via Perija"
}