# Generated by Django 5.1.1 on 2025-07-14 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedulaCliente",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                ("nombreCliente", models.CharField(max_length=100)),
                ("direccionCliente", models.CharField(max_length=255)),
                ("telefonoCliente", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACT", "Activo"), ("DES", "Desactivo")],
                        default="ACT",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estadoCompra",
                    models.CharField(
                        choices=[("VAL", "Valido"), ("ANUL", "Anulado")],
                        default="VAL",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreEmpleado", models.CharField(max_length=100)),
                (
                    "cedulaEmpleado",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                ("direccionEmpleado", models.CharField(max_length=150)),
                ("telefonoEmpleado", models.CharField(max_length=100)),
                ("emailEmpleado", models.EmailField(max_length=250)),
                (
                    "nivelAutorizacion",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("EMP", "Empleado")],
                        default="EMP",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreProducto", models.CharField(max_length=100)),
                (
                    "codigoProducto",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                ("stock", models.PositiveIntegerField()),
                (
                    "precioProducto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rifProveedor",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                ("nombreProveedor", models.CharField(max_length=100)),
                ("emailProveedor", models.EmailField(max_length=250)),
                ("telefonoProveedor", models.CharField(max_length=100)),
                ("direccionProveedor", models.CharField(max_length=250)),
                ("fechaRegistro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigoServicio",
                    models.PositiveBigIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999),
                        ],
                    ),
                ),
                (
                    "precioServicio",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("nombreServicio", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "empleado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.empleado"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetalleVentaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "nombreProducto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "precioProducto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleCompraProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "nombreProducto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "precioProducto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemsProductosCompra",
                        to="api.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="productos",
            field=models.ManyToManyField(
                related_name="comprasProductos",
                through="api.DetalleCompraProducto",
                to="api.producto",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="idProveedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.proveedor",
            ),
        ),
        migrations.CreateModel(
            name="DetalleVentaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "nombreServicio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "precioServicio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estadoVenta",
                    models.CharField(
                        choices=[("VAL", "Valido"), ("ANUL", "Anulado")],
                        default="VAL",
                        max_length=4,
                    ),
                ),
                (
                    "idCliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cliente",
                    ),
                ),
                (
                    "idEmpleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.empleado",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        related_name="ventasProductos",
                        through="api.DetalleVentaProducto",
                        to="api.producto",
                    ),
                ),
                (
                    "servicios",
                    models.ManyToManyField(
                        related_name="ventasServicios",
                        through="api.DetalleVentaServicio",
                        to="api.servicio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detalleventaservicio",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemsServicio",
                to="api.venta",
            ),
        ),
        migrations.AddField(
            model_name="detalleventaproducto",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemsProductos",
                to="api.venta",
            ),
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCliente", models.CharField(max_length=100)),
                ("cedulaCliente", models.PositiveIntegerField()),
                (
                    "ventaDetalle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.venta"
                    ),
                ),
            ],
        ),
    ]
