# Generated by Django 5.0.2 on 2025-05-10 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedulaCliente', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('nombreCliente', models.CharField(max_length=100)),
                ('direccionCliente', models.CharField(max_length=255)),
                ('telefonoCliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('DES', 'Desactivo')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpleado', models.CharField(max_length=100)),
                ('cedulaEmpleado', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('direccionEmpleado', models.CharField(max_length=150)),
                ('telefonoEmpleado', models.CharField(max_length=100)),
                ('emailEmpleado', models.EmailField(max_length=250)),
                ('nivelAutorizacion', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMP', 'Empleado')], default='EMP', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('stock', models.PositiveIntegerField()),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoServicio', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('precioServicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombreServicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estadoVenta', models.CharField(choices=[('VAL', 'Valido'), ('ANUL', 'Anulado')], default='VAL', max_length=4)),
                ('idCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('idEmpleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
                ('productos', models.ManyToManyField(related_name='ventasProductos', through='api.DetalleVentaProducto', to='api.producto')),
                ('servicios', models.ManyToManyField(related_name='ventasServicios', through='api.DetalleVentaServicio', to='api.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventaservicio',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itermsServicio', to='api.venta'),
        ),
        migrations.AddField(
            model_name='detalleventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsProductos', to='api.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('cedulaCliente', models.PositiveIntegerField()),
                ('ventaDetalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
    ]
