# Generated by Django 5.1.1 on 2025-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detalleventaservicio_nombreservicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riffProveedor', models.PositiveIntegerField()),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('telefonoProveedor', models.CharField(max_length=100)),
                ('direccionProveedor', models.CharField(max_length=250)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
