# Generated by Django 5.1.1 on 2025-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_usuario_empleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasaCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="tasaCambio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="tasaCambio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="emailEmpleado",
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="emailProveedor",
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
