# Generated by Django 5.1.1 on 2025-07-01 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='riffProveedor',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
