# Generated by Django 5.1.1 on 2025-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tasacambio_compra_tasacambio_venta_tasacambio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="tasaCambio",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tasaCambio",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
