# Generated by Django 5.1.1 on 2025-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_proveedor_riffproveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='riffProveedor',
            new_name='rifProveedor',
        ),
    ]
