# Generated by Django 5.1.1 on 2025-07-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_riffproveedor_proveedor_rifproveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='email',
            new_name='emailProveedor',
        ),
    ]
