# Generated by Django 5.1.1 on 2025-07-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_email_proveedor_emailproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estadoCompra', models.CharField(choices=[('VAL', 'Valido'), ('ANUL', 'Anulado')], default='VAL', max_length=4)),
                ('idProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsProductosCompra', to='api.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(related_name='comprasProductos', through='api.DetalleCompraProducto', to='api.producto'),
        ),
    ]
