# Generated by Django 5.1.1 on 2025-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_detalleventaproducto_nombreproducto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallecompraproducto",
            name="nombreProducto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="detallecompraproducto",
            name="precioProducto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
