# Generated by Django 5.1.1 on 2025-07-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_detallecompraproducto_nombreproducto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventaproducto",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.producto",
            ),
        ),
    ]
