# Generated by Django 5.1.1 on 2025-07-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_detalleventaproducto_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallecompraproducto",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.producto",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventaservicio",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.servicio",
            ),
        ),
    ]
